db:
  dsn: "host=localhost user=jcourse password=jcoursepassword dbname=jcourse port=5432 sslmode=disable TimeZone=Asia/Shanghai"
redis:
  addr: "redis"
  port: 6379
  password: ""
  db: 0
smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  sender: "noreply@jcourse.com"
event:
  enabled: true