db:
  dsn: "jcourse:jcoursepassword@tcp(localhost:3306)/jcourse_dev?charset=utf8mb4&parseTime=True&loc=Local"
redis:
  addr: "localhost"
  port: 6379
  password: ""
  db: 0
smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  sender: "noreply@jcourse.com"